[mypy]
python_version = 3.12
strict = True
plugins = pydantic.mypy
mypy_path = packages/protocol/src:packages/server/src:packages/client/src
explicit_package_bases = True
namespace_packages = True

[mypy-tests.*]
disallow_untyped_decorators = False
